-- NOTE: This file is auto generated by ./sql-generator

-- AssetLockRestoreRepository.snapshot
insert into
  "asset_lock_restore" ("assetId", "priorVisibility", "priorAlbumIds")
select
  "asset"."id",
  "asset"."visibility",
  array(
    select
      "album_asset"."albumId"
    from
      "album_asset"
    where
      "album_asset"."assetId" = "asset"."id"
  ) as "priorAlbumIds"
from
  "asset"
where
  "asset"."id" = any ($1::uuid[])
  and "asset"."visibility" != $2
on conflict ("assetId") do nothing

-- AssetLockRestoreRepository.getMany
select
  "asset_lock_restore"."assetId",
  "asset_lock_restore"."priorVisibility",
  array(
    select
      "album"."id"
    from
      "album"
    where
      "album"."id" = any ("asset_lock_restore"."priorAlbumIds")
      and "album"."deletedAt" is null
      and "album"."isLocked" = false
  ) as "priorAlbumIds",
  coalesce(
    array_length("asset_lock_restore"."priorAlbumIds", 1),
    0
  ) as "priorAlbumCount"
from
  "asset_lock_restore"
where
  "asset_lock_restore"."assetId" = any ($1::uuid[])

-- AssetLockRestoreRepository.deleteMany
delete from "asset_lock_restore"
where
  "assetId" = any ($1::uuid[])
